### ISSUE TITLE
Icons are assumed to be in root

### ISSUE THREAD

**Issue by alecthomas** [onweru/compose#53]
Similar to #49, the icons for code blocks are assumed to be in the root and when using an alternate `baseURL` they do not work but also seem to corrupt most of the page. Chrome console:

![image](https://user-images.githubusercontent.com/41767/119109899-f253b480-ba64-11eb-877a-6e57230df216.png)

**Comment by alecthomas** [comment]
I believe the same is also true for the search index `/index.json`.

**Comment by safaci2000** [comment]
I also ran into the same issue.

themes/compose/assets/js/variables.js:const rootURL = window.location.protocol + "//" + window.location.host; 

That line is what's used instead of pulling the value from Hugo's settings.  It screws everything up when you have a relative path.  You can probably just hard code that line to be:

rootURL = window.location.protocol + "//" + window.location.host + "/relativePath";.  It's not pretty but it would work.

**Comment by safaci2000** [comment]
I can confirm that changing the rootURL provides a fix, though as I said, probably should find a better way of fixing it.

**Comment by onweru** [comment]
fixed via #69
