### ISSUE TITLE
[BUG] Page Title is overlapped by Page Menu

### ISSUE THREAD

**Issue by illusion0001** [onweru/compose#90]
**I have checked all the prerequisites below and I'm yet experiencing a problem**

- [x] Read the README.md
- [x] Have the extended version of Hugo installed
- [x] Used the exampleSite's config.toml as a reference

**Describe the bug**

On mobile, the menu is overlapping the page title. Example: https://docs.neuralvibes.com/blog/creating-a-new-theme/

![](https://user-images.githubusercontent.com/37698908/214283870-1313dfd3-8211-4c75-8ee9-78dca0ec4c2b.png)

**Mobile:**
 - OS: Android 11
 - Browser: Chrome 109

**Comment by illusion0001** [comment]
Hm, I cloned newest commit and it is still `-1` for me. I tried clearing `resources` folder but it still generated with `-1`
![image](https://user-images.githubusercontent.com/37698908/214384932-5c4dc198-c58e-41c0-9577-cfaca3356052.png)

**Comment by onweru** [comment]
@illusion0001, please try again and let me know.

**Comment by illusion0001** [comment]
Thanks, works now 👍

**Comment by ltGuillaume** [comment]
@onweru The issue is still present to some extent, `1.75rem` is not enough.

See current `1.75rem`
![image](https://user-images.githubusercontent.com/4777345/216720084-20341bfa-8d11-436e-b535-74952efc3a64.png)

vs `2rem` (1.9 is the minimum):
![image](https://user-images.githubusercontent.com/4777345/216720335-162854bc-a792-4c49-adca-8c364bf11538.png)
